balance_features = [
    "date",
    "symbol",
    "reportedCurrency",
    "cik",
    "fillingDate",
    "acceptedDate",
    "calendarYear",
    "period",
    # current assets
    "cashAndCashEquivalents",
    "shortTermInvestments",
    "cashAndShortTermInvestments",
    "netReceivables",
    "inventory",
    "otherCurrentAssets",
    "totalCurrentAssets",
    # long term assets
    "propertyPlantEquipmentNet",
    "goodwill",
    "intangibleAssets",
    "goodwillAndIntangibleAssets",
    "longTermInvestments",
    "taxAssets",
    "otherNonCurrentAssets",
    "totalNonCurrentAssets",
    "otherAssets",
    "totalAssets",
    # current liabilities (due in 1 year or less)
    "accountPayables",# money owed to vendors
    "shortTermDebt",
    "taxPayables",
    "deferredRevenue",# cash received in advanced but not yet earned
    "otherCurrentLiabilities",
    "totalCurrentLiabilities",
    # long term liabilities
    "longTermDebt",
    "deferredRevenueNonCurrent", #cash received in advanced but not yet earned more that 1 year
    "deferredTaxLiabilitiesNonCurrent",
    "otherNonCurrentLiabilities",
    "totalNonCurrentLiabilities",
    "otherLiabilities",
    "capitalLeaseObligations", # obligations related to a lease (contract entitling a renter to the temporary use of an asset)
    "totalLiabilities",
    # Equity
    "preferredStock", # receive dividends before common stock
    "commonStock",
    "retainedEarnings", # sum of all previous proftis and losses minus dividends
    "accumulatedOtherComprehensiveIncomeLoss", # complicated
    "othertotalStockholdersEquity", 
    "totalStockholdersEquity", # 
    "totalLiabilitiesAndStockholdersEquity",
    "minorityInterest",
    "totalEquity",
    "totalLiabilitiesAndTotalEquity",
    "totalInvestments",
    "totalDebt",
    "netDebt",
    "link",
    "finalLink",
]
cash_flow_features = [
    "date",
    "symbol",
    "reportedCurrency",
    "cik",
    "fillingDate",
    "acceptedDate",
    "calendarYear",
    "period",
    # operating cash flow
    "netIncome",
    "depreciationAndAmortization",
    "deferredIncomeTax",
    "stockBasedCompensation",
    "changeInWorkingCapital",
    "accountsReceivables",
    "inventory",
    "accountsPayables",
    "otherWorkingCapital",
    "otherNonCashItems",
    "netCashProvidedByOperatingActivities",
    # investing cash flow
    "investmentsInPropertyPlantAndEquipment", # purchase of PP&E
    "acquisitionsNet", # acquisitions of businesses
    "purchasesOfInvestments", # buy government bonds for instance
    "salesMaturitiesOfInvestments",
    "otherInvestingActivites",
    "netCashUsedForInvestingActivites",
    # finance cash flow
    "debtRepayment",
    "commonStockIssued",
    "commonStockRepurchased",
    "dividendsPaid",
    "otherFinancingActivites",
    "netCashUsedProvidedByFinancingActivities",
    "effectOfForexChangesOnCash",
    "netChangeInCash",
    "cashAtEndOfPeriod",
    "cashAtBeginningOfPeriod",
    "operatingCashFlow", # duplicated from above
    "capitalExpenditure", # PP&E adding disposals of PP&E
    "freeCashFlow", # CFO - Capex
    "link",
    "finalLink",
]

income_features = [
    "date",
    "symbol",
    "reportedCurrency",
    "cik",
    "fillingDate",
    "acceptedDate",
    "calendarYear",
    "period",
    "revenue",
    "costOfRevenue",
    "grossProfit",
    "grossProfitRatio",
    "researchAndDevelopmentExpenses",
    "generalAndAdministrativeExpenses",
    "sellingAndMarketingExpenses",
    "sellingGeneralAndAdministrativeExpenses",
    "otherExpenses",
    "operatingExpenses",
    "costAndExpenses",
    "interestIncome",
    "interestExpense",
    "depreciationAndAmortization",
    "ebitda",
    "ebitdaratio",
    "operatingIncome",
    "operatingIncomeRatio",
    "totalOtherIncomeExpensesNet",
    "incomeBeforeTax",
    "incomeBeforeTaxRatio",
    "incomeTaxExpense",
    "netIncome",
    "netIncomeRatio",
    "eps",
    "epsdiluted",
    "weightedAverageShsOut",
    "weightedAverageShsOutDil",
    "link",
    "finalLink",
]

balance_numerical_features = [
    # "date",
    # "symbol",
    # "reportedCurrency",
    # "cik",
    # "fillingDate",
    # "acceptedDate",
    # "calendarYear",
    # "period",
    "cashAndCashEquivalents",
    "shortTermInvestments",
    "cashAndShortTermInvestments",
    "netReceivables",
    "inventory",
    "otherCurrentAssets",
    "totalCurrentAssets",
    "propertyPlantEquipmentNet",
    "goodwill",
    "intangibleAssets",
    "goodwillAndIntangibleAssets",
    "longTermInvestments",
    "taxAssets",
    "otherNonCurrentAssets",
    "totalNonCurrentAssets",
    "otherAssets",
    "totalAssets",
    "accountPayables",
    "shortTermDebt",
    "taxPayables",
    "deferredRevenue",
    "otherCurrentLiabilities",
    "totalCurrentLiabilities",
    "longTermDebt",
    "deferredRevenueNonCurrent",
    "deferredTaxLiabilitiesNonCurrent",
    "otherNonCurrentLiabilities",
    "totalNonCurrentLiabilities",
    "otherLiabilities",
    "capitalLeaseObligations",
    "totalLiabilities",
    "preferredStock",
    "commonStock",
    "retainedEarnings",
    "accumulatedOtherComprehensiveIncomeLoss",
    "othertotalStockholdersEquity",
    "totalStockholdersEquity",
    "totalLiabilitiesAndStockholdersEquity",
    "minorityInterest",
    "totalEquity",
    "totalLiabilitiesAndTotalEquity",
    "totalInvestments",
    "totalDebt",
    "netDebt",
    # "link",
    # "finalLink",
]

cash_flow_numerical_features = [
    # "date",
    # "symbol",
    # "reportedCurrency",
    # "cik",
    # "fillingDate",
    # "acceptedDate",
    # "calendarYear",
    # "period",
    "netIncome",
    "depreciationAndAmortization",
    "deferredIncomeTax",
    "stockBasedCompensation",
    "changeInWorkingCapital",
    "accountsReceivables",
    "inventory",
    "accountsPayables",
    "otherWorkingCapital",
    "otherNonCashItems",
    "netCashProvidedByOperatingActivities",
    "investmentsInPropertyPlantAndEquipment",
    "acquisitionsNet",
    "purchasesOfInvestments",
    "salesMaturitiesOfInvestments",
    "otherInvestingActivites",
    "netCashUsedForInvestingActivites",
    "debtRepayment",
    "commonStockIssued",
    "commonStockRepurchased",
    "dividendsPaid",
    "otherFinancingActivites",
    "netCashUsedProvidedByFinancingActivities",
    "effectOfForexChangesOnCash",
    "netChangeInCash",
    "cashAtEndOfPeriod",
    "cashAtBeginningOfPeriod",
    "operatingCashFlow",
    "capitalExpenditure",
    "freeCashFlow",
    # "link",
    # "finalLink",
]

income_numerical_features = [
    # "date",
    # "symbol",
    # "reportedCurrency",
    # "cik",
    # "fillingDate",
    # "acceptedDate",
    # "calendarYear",
    # "period",
    "revenue",
    "costOfRevenue",
    "grossProfit",
    "grossProfitRatio",
    "researchAndDevelopmentExpenses",
    "generalAndAdministrativeExpenses",
    "sellingAndMarketingExpenses",
    "sellingGeneralAndAdministrativeExpenses",
    "otherExpenses",
    "operatingExpenses",
    "costAndExpenses",
    "interestIncome",
    "interestExpense",
    "depreciationAndAmortization",
    "ebitda",
    "ebitdaratio",
    "operatingIncome",
    "operatingIncomeRatio",
    "totalOtherIncomeExpensesNet",
    "incomeBeforeTax",
    "incomeBeforeTaxRatio",
    "incomeTaxExpense",
    "netIncome",
    "netIncomeRatio",
    "eps",
    "epsdiluted",
    "weightedAverageShsOut",
    "weightedAverageShsOutDil",
    # "link",
    # "finalLink",
]

currency_features = [
    'cashAndCashEquivalents',
    'shortTermInvestments',
    'cashAndShortTermInvestments',
    'netReceivables',
    'inventory',
    'otherCurrentAssets',
    'totalCurrentAssets',
    'propertyPlantEquipmentNet',
    'goodwill',
    'intangibleAssets',
    'goodwillAndIntangibleAssets',
    'longTermInvestments',
    'taxAssets',
    'otherNonCurrentAssets',
    'totalNonCurrentAssets',
    'otherAssets',
    'totalAssets',
    'accountPayables',
    'shortTermDebt',
    'taxPayables',
    'deferredRevenue',
    'otherCurrentLiabilities',
    'totalCurrentLiabilities',
    'longTermDebt',
    'deferredRevenueNonCurrent',
    'deferredTaxLiabilitiesNonCurrent',
    'otherNonCurrentLiabilities',
    'totalNonCurrentLiabilities',
    'otherLiabilities',
    'capitalLeaseObligations',
    'totalLiabilities',
    'retainedEarnings',
    'accumulatedOtherComprehensiveIncomeLoss',
    'othertotalStockholdersEquity',
    'totalStockholdersEquity',
    'totalLiabilitiesAndStockholdersEquity', # drop candidate
    'minorityInterest',
    'totalEquity',
    'totalLiabilitiesAndTotalEquity', # drop candidate
    'totalInvestments',
    'totalDebt',
    'netDebt',
    'revenue',
    'costOfRevenue',
    'grossProfit',
    'researchAndDevelopmentExpenses',
    'generalAndAdministrativeExpenses',
    'sellingAndMarketingExpenses',
    'sellingGeneralAndAdministrativeExpenses',
    'otherExpenses',
    'operatingExpenses',
    'costAndExpenses',
    'interestIncome',
    'interestExpense',
    'depreciationAndAmortization',
    'ebitda',
    'operatingIncome',
    'totalOtherIncomeExpensesNet',
    'incomeBeforeTax',
    'incomeBeforeTaxRatio',
    'incomeTaxExpense',
    'netIncome',
    'deferredIncomeTax',
    'stockBasedCompensation',
    'changeInWorkingCapital',
    'accountsReceivables',
    'accountsPayables',
    'otherWorkingCapital',
    'otherNonCashItems',
    'netCashProvidedByOperatingActivities',
    'investmentsInPropertyPlantAndEquipment',
    'acquisitionsNet',
    'purchasesOfInvestments',
    'salesMaturitiesOfInvestments',
    'otherInvestingActivites',
    'netCashUsedForInvestingActivites',
    'debtRepayment',
    'commonStockIssued',
    'commonStockRepurchased',
    'dividendsPaid',
    'otherFinancingActivites',
    'netCashUsedProvidedByFinancingActivities',
    'effectOfForexChangesOnCash',
    'netChangeInCash',
    'cashAtEndOfPeriod',
    'cashAtBeginningOfPeriod',
    'operatingCashFlow',
    'capitalExpenditure',
    'freeCashFlow',
]